### ISSUE TITLE
Possible issue with both a DragEnter and DragLeave for the same element

### ISSUE THREAD

**Issue by hpinsley** [norpan/elm-html5-drag-drop#1]
This library works great.  Thank you for writing it!  

I seem to be having some difficultly whereby **sometimes** I get a DragEnter and DragLeave when hovering over a droppable element (in my case a TR).  I haven't been able to put my finger on exactly what is going on, but perhaps these log messages illustrate a bit.

These are the log messages when a drag and drop works properly:

```
app.js:12691 dragDropMsg: DragStart { bucketId = "Manual-56", startTime = 1487615992883, endTime = 1487615993884 }
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: DragEnter "Manual-54"
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: Drop
app.js:12691 with Result: Just ({ bucketId = "Manual-56", startTime = 1487615992883, endTime = 1487615993884 },"Manual-54")
app.js:12691 drop: ({ bucketId = "Manual-56", startTime = 1487615992883, endTime = 1487615993884 },"Manual-54")
app.js:12691 dragDropMsg: DragEnd
app.js:12691 with Result: Nothing
```

and this is a somewhat equivalent case of one that doesn't work

```
app.js:12691 dragDropMsg: DragStart { bucketId = "Manual-29", startTime = 1487615985884, endTime = 1487615991886 }
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: DragEnter "Manual-43"
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: DragEnter "Manual-43"
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: DragLeave "Manual-43"
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: DragEnter "Manual-43"
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: DragLeave "Manual-43"
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: Drop
app.js:12691 with Result: Nothing
app.js:12691 dragDropMsg: DragEnd
app.js:12691 with Result: Nothing
```

I think the problem is that I am getting a pre-mature or erroneous DragLeave event.  This was an attempt to drop an item on "Manual-43".  But, as you can see, it appears that it is getting a DragLeave as soon as it gets the DragEnter (or quickly thereafter).  

I'm dragging within a nested TD that is itself nested in an outer table and I'm dropping on an outer table TR.  I think this has something to do with the contents of the child elements.  The only thing I came up with while researching this is that some people have had issues where DragLeave was being issued because child elements were grabbing the DragEnter event?  I honestly don't know if this is a general issue with drag/drop or the implementation here, or some complication with the fact that the DOM is virtual and pieces of the real DOM are generated by Elm.

**Comment by norpan** [comment]
Thanks for reporting this!
I've made a new version where we take the id from the actual drop message, so it should be more robust. Maybe it can be tolerated that `getDropId` is a bit unreliable.

Otherwise it may be possible to get all the ondragover messages, but I've avoided them because they are emitted a lot.

**Comment by hpinsley** [comment]
It does indeed seem to work better.  Thanks for the fix!
