### ISSUE TITLE
DragOver flooding the runtime

### ISSUE THREAD

**Issue by Hermanverschooten** [norpan/elm-html5-drag-drop#10]
I noticed a serious delay when using drag drop with a highlight on the droppable items.
It seems the runtime gets flooded with DragOver messages.
In the following video I drag an item and the destination should turn dark grey when I hover over it.
Now it turns grey some time after I have already dropped.

![ezgif-3-1485533a409d](https://user-images.githubusercontent.com/91784/47499163-93534200-d85f-11e8-8c45-6e36c7b9423b.gif)

**Comment by Hermanverschooten** [comment]
As suggested in our Slack conversation I tried following:

Only update the DragDrop Model if it has really changed.

Use Html.lazy on the view, so it does not re-render all the time.

This made it a lot faster, but still the lag is noticeable.

**Comment by norpan** [comment]
Fixed by not stopping propagation so that events are handled async.
