### ISSUE TITLE
Dragging a child drags the parent instead

### ISSUE THREAD

**Issue by tias79** [norpan/elm-html5-drag-drop#11]
If I have a draggable element with a draggable child element, there seems to be no way of stopping the propagation of the ondragstart event on the child, making the parent element being dragged when I actually intended to drag the child element. The child element is a div inside a parent div.

I'm experiencing this with elm-html5-drag-drop 3.0.0 and Elm 0.19 in Chrome. Is there some mechanism for controlling this that I'm looking past?

**Comment by norpan** [comment]
I'll make a new version in which dragstart propagation is stopped so you can try it out. This is a use case scenario I haven't considered, but I can't see any reasonable scenario where you would actually need propagation from one draggable to another, that's just confusing.

**Comment by norpan** [comment]
Made a new version 3.0.2. https://github.com/norpan/elm-html5-drag-drop/commit/f85518c40c376804314913ae8e1b53caa946b4a3

**Comment by tias79** [comment]
Excellent! Works like a charm!
