### ISSUE TITLE
Droppable fires for both parent and child

### ISSUE THREAD

**Issue by pirovorster** [norpan/elm-html5-drag-drop#17]
I have a hierarchy of divs. When I drag an item on a droppable child it oscillates between the parent and the child.

So for example:
![image](https://user-images.githubusercontent.com/6638988/52979481-7b8b6500-33de-11e9-86e8-c52cda3aef85.png)
If I drag an item over SomeName2 it gives the following console.logs

> (dropId, position): (Just "Horizontal Layout",Just { height = 102, width = 211, x = 69, y = 14 })
> (dropId, position): (Just "SomeName2 (Dropdown)",Just { height = 44, width = 79, x = 69, y = 14 })
> (dropId, position): (Just "Horizontal Layout",Just { height = 102, width = 211, x = 69, y = 14 })
> (dropId, position): (Just "SomeName2 (Dropdown)",Just { height = 44, width = 79, x = 69, y = 14 })

I suspect its a similar issue to https://github.com/norpan/elm-html5-drag-drop/issues/11 where the propagation is not stopped.

**Comment by pirovorster** [comment]
When I change line 256 to
`    , onWithOptions "dragover" { stopPropagation = True, preventDefault = True } <| Json.map wrap <| Json.map2 (DragOver dropId) timeStampDecoder positionDecoder
`
it works as expected,  but I have noted your comment

>     -- We don't stop propagation for dragover events because this will trigger redraw,
>     -- and we get a lot of dragover events.

I am not sure what this means. Could you please elaborateL

**Comment by norpan** [comment]
The issue is that if we stop propagation of the dragover events, they will be handled synchronously, that is, Elm will trigger a redraw for _each_ dragover event. This leads to unacceptable performance in some use cases.

I’ve tried to avoid those extra events by comparing the event timestamps, maybe this does not work properly yet. Maybe there is some better way to do it. I’d love a full example so that I can see if I can do anything about it.

The actual drop event should be for the right element though.

**Comment by pirovorster** [comment]
Just for interest sake, why does elm trigger a redraw when prorogation is
stopped?

I will try and compile a smaller example.

The drop event does have the correct value. I however need to style my
borders based on the drop location while hovering.

**Comment by pirovorster** [comment]
Could you maybe make it configurable in case one needs to have the stop propogation if the performance issue is acceptable.

**Comment by norpan** [comment]
I would rather have it fixed than a hard-to-understand configuration. My advice is that you either fix the version of the package or copy the module to your project, it’s just one file, after all.

**Comment by norpan** [comment]
There are complicated technical reasons why stop propagation also implies direct redraw. Some of it has to do with text inputs, as I understand it.

**Comment by pirovorster** [comment]
I already have a copy of the module working in my copy. So no worries. I will still and provide an example at some point in time. Thank you.
