### ISSUE TITLE
How to know when hovering over a dropzone?

### ISSUE THREAD

**Issue by Oddsor** [norpan/elm-html5-drag-drop#3]
So I have a situation where I would like to use the model type to check which dropzone is hovered. For instance when hovering a draggable element over a dropzone I would like to apply a highlight-style to said element.

One way I thought of to solve this is to check if the model is DraggedOver a specific element, but the DraggedOver type is not exposed in this module!

Could the "module exposing"-line be changed to include "Model(..)"?

**Comment by norpan** [comment]
`DraggedOver` is not exposed, but I think `getDropId` should be what you want.

**Comment by Oddsor** [comment]
aha! of course I can use that one. For some reason I completely overlooked those two functions. Thanks!
