### ISSUE TITLE
Would you allow dropping of external elements?

### ISSUE THREAD

**Issue by dewyze** [norpan/elm-html5-drag-drop#4]
Would you be open to merging a pull request that allowed for the ability to drag/drop something like an external file or photo into a dropzone?

It would also need to be able to be configurable where this behavior needs to be explicitly enabled.

I would be interested in adding this, but only if you find this useful.

**Comment by norpan** [comment]
Hi! 
I think that is outside the scope of this package, so it's probably better to make a separate package for that.
