### ISSUE TITLE
Linked Ellie Example fails on several occasions

### ISSUE THREAD

**Issue by PixelPartner** [norpan/elm-html5-drag-drop#7]
When I compile and run the example with elm 0.18 I have the following effects:

- Dragging the Logo down replaces the whole page with the SVG file.
- Dragging an empty div results in redirect to http://0.0.0.0

**Comment by PixelPartner** [comment]
Okay, I looked up the closed issues and followed the recommendation to use the latest package version in Ellie. With using `1.1.0` it now also works in latest Firefox.
So, please fix the Ellie.

**Comment by norpan** [comment]
I've released a new version now.

**Comment by PixelPartner** [comment]
Many thanks. This will help ellie beginners like me be less confused.
